apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./apps/cert-manager.yaml
  - ./apps/external-secrets.yaml
  - https://raw.githubusercontent.com/external-secrets/bitwarden-sdk-server/refs/tags/v0.3.1/hack/cluster_issuer.yaml
  - https://raw.githubusercontent.com/external-secrets/bitwarden-sdk-server/refs/tags/v0.3.1/hack/bitwarden-certificate.yaml
