apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./apps/cert-manager.yaml
  - ./apps/external-secrets.yaml
  - https://github.com/external-secrets/bitwarden-sdk-server/hack/cluster_issuer.yaml?ref=v0.3.1
  - https://github.com/external-secrets/bitwarden-sdk-server/hack/bitwarden-certificate.yaml?ref=v0.3.1
